In [262]:
import pandas as pd
import numpy as np

In [2]:
data = [['0', 'Y', 'N'], ['1', 'Y', 'Y'], ['2', 'N', 'Y'], ['3', 'Y', 'Y'], ['4', 'N', 'N']]
df = pd.DataFrame(data, columns=['product_id', 'low_fats', 'recyclable']).astype({'product_id':'int64', 'low_fats':'category', 'recyclable':'category'})

In [3]:
data

[['0', 'Y', 'N'],
 ['1', 'Y', 'Y'],
 ['2', 'N', 'Y'],
 ['3', 'Y', 'Y'],
 ['4', 'N', 'N']]

In [4]:
df

   product_id low_fats recyclable
0           0        Y          N
1           1        Y          Y
2           2        N          Y
3           3        Y          Y
4           4        N          N

In [5]:
df['product_id']

0    0
1    1
2    2
3    3
4    4
Name: product_id, dtype: int64

In [6]:
type(df)

pandas.core.frame.DataFrame

In [7]:
df[['product_id']]

   product_id
0           0
1           1
2           2
3           3
4           4

In [8]:
"""
def find_customer_referee(customer: pd.DataFrame) -> pd.DataFrame:
    df= customer
    fc= (df['referee_id'].isnull()) | (df['referee_id']!=2)
    return df[fc][['name']]
    
"""

"\ndef find_customer_referee(customer: pd.DataFrame) -> pd.DataFrame:\n    df= customer\n    fc= (df['referee_id'].isnull()) | (df['referee_id']!=2)\n    return df[fc][['name']]\n    \n"

In [9]:
"""
def big_countries(world: pd.DataFrame) -> pd.DataFrame:
    df = world
    fc = ((df['area']>=3000000) | (df['population']>=25000000))
    return df[fc][['name','population','area']]
"""

"\ndef big_countries(world: pd.DataFrame) -> pd.DataFrame:\n    df = world\n    fc = ((df['area']>=3000000) | (df['population']>=25000000))\n    return df[fc][['name','population','area']]\n"

In [15]:
data = [[1, 3, 5, '2019-08-01'],
        [1, 3, 6, '2019-08-02'], 
        [2, 7, 7, '2019-08-01'],
        [2, 7, 6, '2019-08-02'],
        [4, 7, 1, '2019-07-22'],
        [3, 4, 4, '2019-07-21'], 
        [3, 4, 4, '2019-07-21']]


views = pd.DataFrame(data, columns=['article_id', 'author_id', 'viewer_id', 'view_date']).astype({'article_id':'Int64', 'author_id':'Int64', 'viewer_id':'Int64', 'view_date':'datetime64[ns]'})

In [16]:
type(data)

list

In [17]:
def article_views(views: pd.DataFrame) -> pd.DataFrame:
    df=views
    fc=df['author_id']==df['viewer_id']
    output=df[fc][['author_id']].drop_duplicates().sort_values(by ='author_id')
    output= output.rename(columns = {"author_id" : "id" } )
    return output

In [20]:
article_views(views)

   id
5   4
2   7

In [23]:
def article_views(views):
    df=views
    fc=df['author_id']==df['viewer_id']
    output=df[fc][['author_id']].drop_duplicates().sort_values(by ='author_id')
    output= output.rename(columns = {"author_id" : "id" } )
    return output

article_views(views)

   id
5   4
2   7

In [24]:
data = [[1, 'Alice'], [7, 'Bob'], [11, 'Meir'], [90, 'Winston'], [3, 'Jonathan']]
employees = pd.DataFrame(data, columns=['id', 'name']).astype({'id':'int64', 'name':'object'})
data = [[3, 1], [11, 2], [90, 3]]
employee_uni = pd.DataFrame(data, columns=['id', 'unique_id']).astype({'id':'int64', 'unique_id':'int64'})

In [29]:
newemployees=pd.merge(left=employees, right=employee_uni,how='left', on ='id')
newemployees[['name','unique_id']]

       name  unique_id
0     Alice        NaN
1       Bob        NaN
2      Meir        2.0
3   Winston        3.0
4  Jonathan        1.0

In [30]:
data = [[1, 100, 2008, 10, 5000], [2, 100, 2009, 12, 5000], [7, 200, 2011, 15, 9000]]
sales = pd.DataFrame(data, columns=['sale_id', 'product_id', 'year', 'quantity', 'price']).astype({'sale_id':'Int64', 'product_id':'Int64', 'year':'Int64', 'quantity':'Int64', 'price':'Int64'})
data = [[100, 'Nokia'], [200, 'Apple'], [300, 'Samsung']]
product = pd.DataFrame(data, columns=['product_id', 'product_name']).astype({'product_id':'Int64', 'product_name':'object'})

In [32]:
def sales_analysis(sales: pd.DataFrame, product: pd.DataFrame) -> pd.DataFrame:
    df1=sales
    df2=product
    df3=pd.merge(left=df1,right=df2,how='left',on='product_id')
    df3=df3[['product_name','year','price']]
    return df3

sales_analysis(sales,product)

  product_name  year  price
0        Nokia  2008   5000
1        Nokia  2009   5000
2        Apple  2011   9000

In [33]:
data = [[1, 23], [2, 9], [4, 30], [5, 54], [6, 96], [7, 54], [8, 54]]
visits = pd.DataFrame(data, columns=['visit_id', 'customer_id']).astype({'visit_id':'Int64', 'customer_id':'Int64'})
data = [[2, 5, 310], [3, 5, 300], [9, 5, 200], [12, 1, 910], [13, 2, 970]]
transactions = pd.DataFrame(data, columns=['transaction_id', 'visit_id', 'amount']).astype({'transaction_id':'Int64', 'visit_id':'Int64', 'amount':'Int64'})

In [35]:
visits

#transactions

   transaction_id  visit_id  amount
0               2         5     310
1               3         5     300
2               9         5     200
3              12         1     910
4              13         2     970

In [45]:
def find_customers(visits: pd.DataFrame, transactions: pd.DataFrame) -> pd.DataFrame:
    df1=pd.merge(left=visits,right=transactions,how='left',on='visit_id')
    fc=df1['transaction_id'].isnull()
    df1=df1[fc][['visit_id','customer_id']]
    df2=df1.groupby('customer_id').agg({'visit_id':'count'}).reset_index()
    df2=df2.rename(columns = {"visit_id" : "count_no_trans"}).sort_values(by='count_no_trans')
    return df2

find_customers(visits,transactions)

   customer_id  count_no_trans
0           30               1
2           96               1
1           54               2

In [72]:
##Write a solution to find all dates' id with higher temperatures compared to its previous dates (yesterday).

data = [[1, '2015-01-01', 10], [2, '2015-01-02', 25], [3, '2015-01-03', 20], [4, '2015-01-04', 30]]
weather = pd.DataFrame(data, columns=['id', 'recordDate', 'temperature']).astype({'id':'Int64', 'recordDate':'datetime64[ns]', 'temperature':'Int64'})

In [66]:
def rising_temperature(weather: pd.DataFrame) -> pd.DataFrame:
    df1=weather
    df1=df1.sort_values(by='recordDate')
    df1['prev_temp']=df1['temperature'].shift(1)
    fc=df1['temperature']>df1['prev_temp']
    return df1[fc]['id']

In [74]:
df1=weather
df1=df1.sort_values(by='recordDate')
df1
#df1['prev_temp']=df1['temperature'].shift(1)
#fc=df1['temperature']>df1['prev_temp']

   id recordDate  temperature
0   1 2015-01-01           10
1   2 2015-01-02           25
2   3 2015-01-03           20
3   4 2015-01-04           30

In [62]:
df1[fc]['id']

   id recordDate  temperature  prev_temp
1   2 2015-01-02           25         10
3   4 2015-01-04           30         20

In [75]:
data = [[0, 0, 'start', 0.712], [0, 0, 'end', 1.52], [0, 1, 'start', 3.14], [0, 1, 'end', 4.12], [1, 0, 'start', 0.55], [1, 0, 'end', 1.55], [1, 1, 'start', 0.43], [1, 1, 'end', 1.42], [2, 0, 'start', 4.1], [2, 0, 'end', 4.512], [2, 1, 'start', 2.5], [2, 1, 'end', 5]]
activity = pd.DataFrame(data, columns=['machine_id', 'process_id', 'activity_type', 'timestamp']).astype({'machine_id':'Int64', 'process_id':'Int64', 'activity_type':'object', 'timestamp':'Float64'})

activity

    machine_id  process_id activity_type  timestamp
0            0           0         start      0.712
1            0           0           end       1.52
2            0           1         start       3.14
3            0           1           end       4.12
4            1           0         start       0.55
5            1           0           end       1.55
6            1           1         start       0.43
7            1           1           end       1.42
8            2           0         start        4.1
9            2           0           end      4.512
10           2           1         start        2.5
11           2           1           end        5.0

In [85]:
df=activity
df1=df[df['activity_type']=='start']
df2=df[df['activity_type']=='end']
df3=pd.merge(left=df1,right=df2,how='left',on=['machine_id','process_id'])
df3['processing_time']=df3['timestamp_y']-df3['timestamp_x']
df3=df3.groupby('machine_id').agg({'processing_time':'mean'}).reset_index()
df3

   machine_id  processing_time
0           0            0.894
1           1            0.995
2           2            1.456

In [86]:
#Write a solution to report the name and bonus amount of each employee who satisfies either of the following:
### The employee has a bonus less than 1000.
### The employee did not get any bonus.

data = [[3, 'Brad', None, 4000], [1, 'John', 3, 1000], [2, 'Dan', 3, 2000], [4, 'Thomas', 3, 4000]]
employee = pd.DataFrame(data, columns=['empId', 'name', 'supervisor', 'salary']).astype({'empId':'Int64', 'name':'object', 'supervisor':'Int64', 'salary':'Int64'})
data = [[2, 500], [4, 2000]]
bonus = pd.DataFrame(data, columns=['empId', 'bonus']).astype({'empId':'Int64', 'bonus':'Int64'})

In [88]:
employee
bonus

   empId  bonus
0      2    500
1      4   2000

In [95]:
df=pd.merge(left=employee,right=bonus,how='left',on='empId')
fc=(df['bonus'].isnull())|(df['bonus']<1000)
df[fc][['name','bonus']]

   name  bonus
0  Brad   <NA>
1  John   <NA>
2   Dan    500

In [104]:
##

data = [[1, 'Alice'], [2, 'Bob'], [13, 'John'], [6, 'Alex']]
students = pd.DataFrame(data, columns=['student_id', 'student_name']).astype({'student_id':'Int64', 'student_name':'object'})
data = [['Math'], ['Physics'], ['Programming']]
subjects = pd.DataFrame(data, columns=['subject_name']).astype({'subject_name':'object'})
data = [[1, 'Math'], [1, 'Physics'], [1, 'Programming'], [2, 'Programming'], [1, 'Physics'], [1, 'Math'], [13, 'Math'], [13, 'Programming'], [13, 'Physics'], [2, 'Math'], [1, 'Math']]
examinations = pd.DataFrame(data, columns=['student_id', 'subject_name']).astype({'student_id':'Int64', 'subject_name':'object'})

In [105]:
students

   student_id student_name
0           1        Alice
1           2          Bob
2          13         John
3           6         Alex

In [111]:
df1=students
df2=subjects
df3=examinations
df3['dummy']=1
df3

    student_id subject_name  dummy
0            1         Math      1
1            1      Physics      1
2            1  Programming      1
3            2  Programming      1
4            1      Physics      1
5            1         Math      1
6           13         Math      1
7           13  Programming      1
8           13      Physics      1
9            2         Math      1
10           1         Math      1

In [115]:
df4=pd.merge(left=df1, right=df2,how='cross')
df5=pd.merge(left=df4,right=df3,how='left',on=['student_id','subject_name'])
df5=df5.groupby(['student_id','student_name','subject_name']).agg({'dummy':'count'}).reset_index()
df5=df5.rename(columns={'dummy':'attended_exams'})
df5

    student_id student_name subject_name  attended_exams
0            1        Alice         Math               3
1            1        Alice      Physics               2
2            1        Alice  Programming               1
3            2          Bob         Math               1
4            2          Bob      Physics               0
5            2          Bob  Programming               1
6            6         Alex         Math               0
7            6         Alex      Physics               0
8            6         Alex  Programming               0
9           13         John         Math               1
10          13         John      Physics               1
11          13         John  Programming               1

In [116]:
def students_and_examinations(students: pd.DataFrame, subjects: pd.DataFrame, examinations: pd.DataFrame) -> pd.DataFrame:
    df1=students
    df2=subjects
    df3=examinations
    df3['dummy']=1
    df4=pd.merge(left=df1, right=df2,how='cross')
    df5=pd.merge(left=df4,right=df3,how='left',on=['student_id','subject_name'])
    df5=df5.groupby(['student_id','student_name','subject_name'],dropna=False).agg({'dummy':'count'}).reset_index()
    df5=df5.rename(columns={'dummy':'attended_exams'})
    return df5

In [140]:
# manager name with 5 direct reportee

data = [[101, 'John', 'A', None], [102, 'Dan', 'A', 101], [103, 'James', 'A', 101], [104, 'Amy', 'A', 101], [105, 'Anne', 'A', 101], [106, 'Ron', 'B', 101]]
employee = pd.DataFrame(data, columns=['id', 'name', 'department', 'managerId']).astype({'id':'Int64', 'name':'object', 'department':'object', 'managerId':'Int64'})

In [141]:
employee

    id   name department  managerId
0  101   John          A       <NA>
1  102    Dan          A        101
2  103  James          A        101
3  104    Amy          A        101
4  105   Anne          A        101
5  106    Ron          B        101

In [148]:
count = employee["managerId"].value_counts()
count = count[count>4]
manager = employee[employee.id.isin(list(count.index))][["name"]]

In [149]:
manager

   name
0  John

In [150]:
##https://leetcode.com/problems/confirmation-rate/?envType=study-plan-v2&envId=top-sql-50

data = [[3, '2020-03-21 10:16:13'], [7, '2020-01-04 13:57:59'], [2, '2020-07-29 23:09:44'], [6, '2020-12-09 10:39:37']]
signups = pd.DataFrame(data, columns=['user_id', 'time_stamp']).astype({'user_id':'Int64', 'time_stamp':'datetime64[ns]'})
data = [[3, '2021-01-06 03:30:46', 'timeout'], [3, '2021-07-14 14:00:00', 'timeout'], [7, '2021-06-12 11:57:29', 'confirmed'], [7, '2021-06-13 12:58:28', 'confirmed'], [7, '2021-06-14 13:59:27', 'confirmed'], [2, '2021-01-22 00:00:00', 'confirmed'], [2, '2021-02-28 23:59:59', 'timeout']]
confirmations = pd.DataFrame(data, columns=['user_id', 'time_stamp', 'action']).astype({'user_id':'Int64', 'time_stamp':'datetime64[ns]', 'action':'object'})

In [152]:
df1=signups
df2=confirmations
df3=pd.merge(left=df1['user_id'], right=df2[['time_stamp', 'action']], how='left', on='user_id')
df3

KeyError: 'user_id'

In [153]:
##Write a solution to report the movies with an odd-numbered ID and a description that is not "boring".

data = [[1, 'War', 'great 3D', 8.9], [2, 'Science', 'fiction', 8.5], [3, 'irish', 'boring', 6.2], [4, 'Ice song', 'Fantacy', 8.6], [5, 'House card', 'Interesting', 9.1]]
cinema = pd.DataFrame(data, columns=['id', 'movie', 'description', 'rating']).astype({'id':'Int64', 'movie':'object', 'description':'object', 'rating':'Float64'})

In [154]:
cinema

   id       movie  description  rating
0   1         War     great 3D     8.9
1   2     Science      fiction     8.5
2   3       irish       boring     6.2
3   4    Ice song      Fantacy     8.6
4   5  House card  Interesting     9.1

In [161]:
fc=(cinema['id']%2!=0)&(cinema['description']!='boring')

In [164]:
cinema[fc][['movie']]
df=cinema[fc][['id','movie','description','rating']]
df=df.sort_values(by='rating',ascending=False)
df

   id       movie  description  rating
4   5  House card  Interesting     9.1
0   1         War     great 3D     8.9

In [165]:
## Write a solution to find the average selling price for each product.
#- average_price should be rounded to 2 decimal places.
#-If a product does not have any sold units, its average selling price is assumed to be 0.

data = [[1, '2019-02-17', '2019-02-28', 5], [1, '2019-03-01', '2019-03-22', 20], [2, '2019-02-01', '2019-02-20', 15], [2, '2019-02-21', '2019-03-31', 30]]
prices = pd.DataFrame(data, columns=['product_id', 'start_date', 'end_date', 'price']).astype({'product_id':'Int64', 'start_date':'datetime64[ns]', 'end_date':'datetime64[ns]', 'price':'Int64'})
data = [[1, '2019-02-25', 100], [1, '2019-03-01', 15], [2, '2019-02-10', 200], [2, '2019-03-22', 30]]
units_sold = pd.DataFrame(data, columns=['product_id', 'purchase_date', 'units']).astype({'product_id':'Int64', 'purchase_date':'datetime64[ns]', 'units':'Int64'})

In [166]:
prices

   product_id start_date   end_date  price
0           1 2019-02-17 2019-02-28      5
1           1 2019-03-01 2019-03-22     20
2           2 2019-02-01 2019-02-20     15
3           2 2019-02-21 2019-03-31     30

In [168]:
units_sold

   product_id purchase_date  units
0           1    2019-02-25    100
1           1    2019-03-01     15
2           2    2019-02-10    200
3           2    2019-03-22     30

In [169]:
import pandas as pd
from numpy import where

def average_selling_price(prices: pd.DataFrame, 
                      units_sold: pd.DataFrame) -> pd.DataFrame:

    df = prices.merge(units_sold, how = 'left')                 # <-- 1)
    df['rev'] = df.price * df.units

    df = (df[(df.purchase_date.isna())|                         # <-- 2)
         (df.purchase_date.between(df.start_date, df.end_date))])

    grp = df.groupby('product_id').agg(                         # <-- 3)
                    total_units = ('units', 'sum'),
                      total_rev = ('rev', 'sum')
                    ).reset_index()

    grp['average_price'] = (where(grp.total_units == 0, 0,      # <-- 4)
                     (grp.total_rev/grp.total_units).round(2)))

    return grp.iloc[:,[0,3]]

In [171]:
average_selling_price(prices,units_sold)

   product_id average_price
0           1          6.96
1           2         16.96

In [172]:
df = prices.merge(units_sold, how = 'left')
df

   product_id start_date   end_date  price purchase_date  units
0           1 2019-02-17 2019-02-28      5    2019-02-25    100
1           1 2019-02-17 2019-02-28      5    2019-03-01     15
2           1 2019-03-01 2019-03-22     20    2019-02-25    100
3           1 2019-03-01 2019-03-22     20    2019-03-01     15
4           2 2019-02-01 2019-02-20     15    2019-02-10    200
5           2 2019-02-01 2019-02-20     15    2019-03-22     30
6           2 2019-02-21 2019-03-31     30    2019-02-10    200
7           2 2019-02-21 2019-03-31     30    2019-03-22     30

In [173]:
df=pd.merge(left=prices,right=units_sold,how='left',on='product_id')
df

   product_id start_date   end_date  price purchase_date  units
0           1 2019-02-17 2019-02-28      5    2019-02-25    100
1           1 2019-02-17 2019-02-28      5    2019-03-01     15
2           1 2019-03-01 2019-03-22     20    2019-02-25    100
3           1 2019-03-01 2019-03-22     20    2019-03-01     15
4           2 2019-02-01 2019-02-20     15    2019-02-10    200
5           2 2019-02-01 2019-02-20     15    2019-03-22     30
6           2 2019-02-21 2019-03-31     30    2019-02-10    200
7           2 2019-02-21 2019-03-31     30    2019-03-22     30

In [174]:
df['rev'] = df.price * df.units

In [176]:
df = (df[(df.purchase_date.isna())|
         (df.purchase_date.between(df.start_date, df.end_date))])

In [177]:
df

   product_id start_date   end_date  price purchase_date  units   rev
0           1 2019-02-17 2019-02-28      5    2019-02-25    100   500
3           1 2019-03-01 2019-03-22     20    2019-03-01     15   300
4           2 2019-02-01 2019-02-20     15    2019-02-10    200  3000
7           2 2019-02-21 2019-03-31     30    2019-03-22     30   900

In [178]:
grp = df.groupby('product_id').agg(                      
                    total_units = ('units', 'sum'),
                      total_rev = ('rev', 'sum')
                    ).reset_index()
grp

   product_id  total_units  total_rev
0           1          115        800
1           2          230       3900

In [182]:
#grp['avg_price']=(grp.total_rev/grp.total_units).round(2)
grp['avg_price']=where(grp.total_units == 0, 0, (grp.total_rev/grp.total_units).round(2) )
grp

   product_id  total_units  total_rev avg_price
0           1          115        800      6.96
1           2          230       3900     16.96

In [187]:
grp.iloc[:,[0,3]]

   product_id avg_price
0           1      6.96
1           2     16.96

In [189]:
import pandas as pd

def average_selling_price(prices: pd.DataFrame, units_sold: pd.DataFrame) -> pd.DataFrame:
    units_sold = units_sold.merge(prices, on='product_id', how='left')
    units_sold['matching'] = (units_sold['purchase_date'] >= units_sold['start_date']) & (units_sold['purchase_date'] <= units_sold['end_date'])
    units_sold = units_sold[units_sold['matching']==True]
    units_sold['total_spent'] = units_sold['units']*units_sold['price']
    units_sold = units_sold.groupby('product_id').agg(total_spent=('total_spent', lambda x: sum(x)), total_units=('units', lambda x: sum(x))).reset_index()
    units_sold['average_price'] = round(units_sold['total_spent']/units_sold['total_units'],2)
    prices = pd.DataFrame(columns=['product_id'], data=prices['product_id'].unique())
    return prices.merge(units_sold[['product_id', 'average_price']], on='product_id', how='left').fillna(0)

average_selling_price(prices,units_sold)

   product_id  average_price
0           1           6.96
1           2          16.96

In [200]:
data = [[1, 1], [1, 2], [1, 3], [2, 1], [2, 4]]
project = pd.DataFrame(data, columns=['project_id', 'employee_id']).astype({'project_id':'Int64', 'employee_id':'Int64'})
data = [[1, 'Khaled', 3], [2, 'Ali', 2], [3, 'John', 1], [4, 'Doe', 2]]
employee = pd.DataFrame(data, columns=['employee_id', 'name', 'experience_years']).astype({'employee_id':'Int64', 'name':'object', 'experience_years':'Int64'})

df1=project
df2=employee
df3=pd.merge(left=df1[['project_id','employee_id']],right=df2[['employee_id','name','experience_years']],how='left',on='employee_id')
df3=df3.groupby('project_id').agg({'experience_years':'mean'}).reset_index()
df3

   project_id  experience_years
0           1               2.0
1           2               2.5

In [201]:
def project_employees_i(project: pd.DataFrame, employee: pd.DataFrame) -> pd.DataFrame:
    df1=project
    df2=employee
    df3=pd.merge(left=df1[['project_id','employee_id']],right=df2[['employee_id','name','experience_years']],how='left',on='employee_id')
    df3=df3.groupby('project_id').agg({'experience_years':'mean'}).reset_index()
    df3=df3.rename(columns = {'experience_years':'average_years '})
    return df3[['project_id','average_years ']]

project_employees_i(project,employee)

   project_id  average_years
0           1             2.0
1           2             2.5

In [231]:
###Write a solution to find the percentage of the users registered in each contest rounded to two decimals.
##Return the result table ordered by percentage in descending order. In case of a tie, order it by contest_id in ascending order.

data = [[6, 'Alice'], [2, 'Bob'], [7, 'Alex']]
users = pd.DataFrame(data, columns=['user_id', 'user_name']).astype({'user_id':'Int64', 'user_name':'object'})
data = [[215, 6], [209, 2], [208, 2], [210, 6], [208, 6], [209, 7], [209, 6], [215, 7], [208, 7], [210, 2], [207, 2], [210, 7]]
register = pd.DataFrame(data, columns=['contest_id', 'user_id']).astype({'contest_id':'Int64', 'user_id':'Int64'})

In [247]:
df1=users
df2=register

df3=pd.merge(left=df1, right=df2, how='left', on='user_id')
cnt=df3['user_id'].nunique()

df3

    user_id user_name  contest_id
0         6     Alice         215
1         6     Alice         210
2         6     Alice         208
3         6     Alice         209
4         2       Bob         209
5         2       Bob         208
6         2       Bob         210
7         2       Bob         207
8         7      Alex         209
9         7      Alex         215
10        7      Alex         208
11        7      Alex         210

In [246]:
#df3['total_user']=df3['user_id'].value_counts()
#df3=df3.groupby('contest_id').agg({'user_id':'count'})

#df3=df3.sort_values(by='contest_id', ascending=True)
df3


df4 = df2.groupby('contest_id', as_index=False).agg(count=('user_id','nunique'))
df4
df4['perc']=(df4['count']/len(df1))*100
df5=df4[['contest_id','perc']].sort_values(by=['perc','contest_id'], ascending=(False,True))
df5

   contest_id        perc
1         208  100.000000
2         209  100.000000
3         210  100.000000
4         215   66.666667
0         207   33.333333

In [242]:
def users_percentage(users: pd.DataFrame, register: pd.DataFrame) -> pd.DataFrame:
    df1=users
    df2=register
    df4 = df2.groupby('contest_id', as_index=False).agg(count=('user_id','nunique'))
    df4['perc']=(df4['count']/len(df1))*100
    df5=df4[['contest_id','perc']].sort_values(by=['perc','contest_id'], ascending=(False,True))
    return df5.round(2)

users_percentage(users,register)

   contest_id    perc
1         208  100.00
2         209  100.00
3         210  100.00
4         215   66.67
0         207   33.33

In [243]:
###Write a solution to find each query_name, the quality and poor_query_percentage.
##Both quality and poor_query_percentage should be rounded to 2 decimal places.


data = [['Dog', 'Golden Retriever', 1, 5], ['Dog', 'German Shepherd', 2, 5], ['Dog', 'Mule', 200, 1], ['Cat', 'Shirazi', 5, 2], ['Cat', 'Siamese', 3, 3], ['Cat', 'Sphynx', 7, 4]]
queries = pd.DataFrame(data, columns=['query_name', 'result', 'position', 'rating']).astype({'query_name':'object', 'result':'object', 'position':'Int64', 'rating':'Int64'})

In [244]:
queries

  query_name            result  position  rating
0        Dog  Golden Retriever         1       5
1        Dog   German Shepherd         2       5
2        Dog              Mule       200       1
3        Cat           Shirazi         5       2
4        Cat           Siamese         3       3
5        Cat            Sphynx         7       4

In [ ]:
def queries_stats(queries: pd.DataFrame) -> pd.DataFrame:
    df1=queries
    df2 = df1.groupby('contest_id', as_index=False).agg(count=('user_id','nunique'))
    df4['perc']=(df4['count']/len(df1))*100
    df5=df4[['contest_id','perc']].sort_values(by=['perc','contest_id'], ascending=(False,True))
    return df5.round(2)

queries_stats(users,register)

In [260]:
df1=queries
df2 = df1.groupby('query_name', as_index=False).agg(count=('result','nunique'))
df3=pd.merge(df1,df2,how='left',on='query_name')
df3['quality']=df1['rating']/df1['position']

#The rating column has a value from 1 to 5. Query with rating less than 3 is a poor query.
df3['poor_query_percentage']=(df1['rating']<3)*100

df4=df3.groupby('query_name').agg({'quality':'mean','poor_query_percentage':'mean'}).round(2).reset_index()
df4

  query_name  quality  poor_query_percentage
0        Cat     0.66                  33.33
1        Dog      2.5                  33.33

In [263]:
df1=queries
df1['quality'] = df1['rating'] / df1['position'] + 1e-10
df1['poor'] = np.where(df1['rating']<3,100,0)
df2 = df1.groupby(by='query_name')[['quality','poor']].agg('mean').round(2).reset_index()
df2.rename(columns={'poor':'poor_query_percentage'})
df2

  query_name  quality   poor
0        Cat     0.66  33.33
1        Dog      2.5  33.33

In [264]:
###Write an SQL query to find for each month and country, 
###the number of transactions and their total amount, the number of approved transactions and their total amount.

data = [[121, 'US', 'approved', 1000, '2018-12-18'], [122, 'US', 'declined', 2000, '2018-12-19'], [123, 'US', 'approved', 2000, '2019-01-01'], [124, 'DE', 'approved', 2000, '2019-01-07']]
transactions = pd.DataFrame(data, columns=['id', 'country', 'state', 'amount', 'trans_date']).astype({'id':'Int64', 'country':'object', 'state':'object', 'amount':'Int64', 'trans_date':'datetime64[ns]'})

In [265]:
transactions

    id country     state  amount trans_date
0  121      US  approved    1000 2018-12-18
1  122      US  declined    2000 2018-12-19
2  123      US  approved    2000 2019-01-01
3  124      DE  approved    2000 2019-01-07

In [291]:
df1=transactions
df1['month_num'] = df1['trans_date'].dt.month
df1['year_month'] = df1['trans_date'].dt.to_period('M').astype(str)

df1['stateCnt']=df1['state']
df1['stateCnt']=df1['stateCnt'].str.replace('approved','1').replace('declined','0')

df1['stateCnt']=1
df1['stateCnt']=df1['stateCnt'].astype(int)

df1['approved_trans']=np.where(df1['state']=='approved',1,0)
df1['approved_amount']=np.where(df1['state']=='approved',df1['amount'],0)
df1

,id,country,state,amount,trans_date,month_num,year_month,approved,approved_trans,approved_amount,stateCnt
0,121,US,approved,1000,2018-12-18,12,2018-12,1,1,1000,1
1,122,US,declined,2000,2018-12-19,12,2018-12,0,0,0,1
2,123,US,approved,2000,2019-01-01,1,2019-01,1,1,2000,1
3,124,DE,approved,2000,2019-01-07,1,2019-01,1,1,2000,1

In [293]:
df2=df1.groupby(['year_month','country'],dropna=False).agg({'id':'count','approved_trans':'sum','amount':'sum','approved_amount':'sum'})
df2

                    id  approved_trans  amount approved_amount
year_month country
2018-12    US        2               1    3000            1000
2019-01    DE        1               1    2000            2000
           US        1               1    2000            2000

In [296]:
def monthly_transactions(transactions: pd.DataFrame) -> pd.DataFrame:
    df1=transactions
    df1['year_month'] = df1['trans_date'].dt.to_period('M').astype(str)
    df1['stateCnt']=1
    df1['approved_trans']=np.where(df1['state']=='approved',1,0)
    df1['approved_amount']=np.where(df1['state']=='approved',df1['amount'],0)
    df2=df1.groupby(['year_month','country'],dropna=False).agg({'id':'count','approved_trans':'sum','amount':'sum','approved_amount':'sum'})
    df2=df2.reset_index().rename(columns={'year_month':'month','id':'trans_count','approved_trans':'approved_count','amount':'trans_total_amount','approved_amount':'approved_total_amount'})
    return df2

monthly_transactions(transactions)

,month,country,trans_count,approved_count,trans_total_amount,approved_total_amount
0,2018-12,US,2,1,3000,1000
1,2019-01,DE,1,1,2000,2000
2,2019-01,US,1,1,2000,2000

In [297]:
### If the customer's preferred delivery date is the same as the order date, then the order is called immediate; otherwise, it is called scheduled.

### The first order of a customer is the order with the earliest order date that the customer made. It is guaranteed that a customer has precisely one first order.

### Write a solution to find the percentage of immediate orders in the first orders of all customers, rounded to 2 decimal places.

##https://leetcode.com/problems/immediate-food-delivery-ii/description/?envType=study-plan-v2&envId=top-sql-50

data = [[1, 1, '2019-08-01', '2019-08-02'], [2, 2, '2019-08-02', '2019-08-02'], [3, 1, '2019-08-11', '2019-08-12'], [4, 3, '2019-08-24', '2019-08-24'], [5, 3, '2019-08-21', '2019-08-22'], [6, 2, '2019-08-11', '2019-08-13'], [7, 4, '2019-08-09', '2019-08-09']]
delivery = pd.DataFrame(data, columns=['delivery_id', 'customer_id', 'order_date', 'customer_pref_delivery_date']).astype({'delivery_id':'Int64', 'customer_id':'Int64', 'order_date':'datetime64[ns]', 'customer_pref_delivery_date':'datetime64[ns]'})

In [298]:
delivery

   delivery_id  customer_id order_date customer_pref_delivery_date
0            1            1 2019-08-01                  2019-08-02
1            2            2 2019-08-02                  2019-08-02
2            3            1 2019-08-11                  2019-08-12
3            4            3 2019-08-24                  2019-08-24
4            5            3 2019-08-21                  2019-08-22
5            6            2 2019-08-11                  2019-08-13
6            7            4 2019-08-09                  2019-08-09

In [310]:
###Write a solution to report the fraction of players that logged in again on the day after the day they first logged in, rounded to 2 decimal places. In other words, you need to determine the number of players who logged in on the day immediately following their initial login, and divide it by the number of total players.

data = [[1, 2, '2016-03-01', 5], [1, 2, '2016-03-02', 6], [2, 3, '2017-06-25', 1], [3, 1, '2016-03-02', 0], [3, 4, '2018-07-03', 5]]
activity = pd.DataFrame(data, columns=['player_id', 'device_id', 'event_date', 'games_played']).astype({'player_id':'Int64', 'device_id':'Int64', 'event_date':'datetime64[ns]', 'games_played':'Int64'})

In [311]:
activity

   player_id  device_id event_date  games_played
0          1          2 2016-03-01             5
1          1          2 2016-03-02             6
2          2          3 2017-06-25             1
3          3          1 2016-03-02             0
4          3          4 2018-07-03             5

In [312]:
activity['next_event_date']=activity['event_date'].shift(-1)
activity

   player_id  device_id event_date  games_played next_event_date
0          1          2 2016-03-01             5      2016-03-02
1          1          2 2016-03-02             6      2017-06-25
2          2          3 2017-06-25             1      2016-03-02
3          3          1 2016-03-02             0      2018-07-03
4          3          4 2018-07-03             5             NaT

In [313]:
activity["first"] = activity.groupby("player_id")[['event_date']].transform(min)
activity

   player_id  device_id event_date  games_played next_event_date      first
0          1          2 2016-03-01             5      2016-03-02 2016-03-01
1          1          2 2016-03-02             6      2017-06-25 2016-03-01
2          2          3 2017-06-25             1      2016-03-02 2017-06-25
3          3          1 2016-03-02             0      2018-07-03 2016-03-02
4          3          4 2018-07-03             5             NaT 2016-03-02

In [314]:
activity_2nd_day = activity.loc[activity["first"]+ pd.DateOffset(1) == activity["event_date"]] 
# + pd.DateOffset(1)
activity_2nd_day

   player_id  device_id event_date  games_played next_event_date      first
1          1          2 2016-03-02             6      2017-06-25 2016-03-01

In [315]:
activity.player_id.nunique()

3

In [316]:
pd.DataFrame({"fraction":[round(len(activity_2nd_day) / activity.player_id.nunique(),2)]})

   fraction
0      0.33

In [317]:
###Write a solution to calculate the number of unique subjects each teacher teaches in the university.

data = [[1, 2, 3], [1, 2, 4], [1, 3, 3], [2, 1, 1], [2, 2, 1], [2, 3, 1], [2, 4, 1]]
teacher = pd.DataFrame(data, columns=['teacher_id', 'subject_id', 'dept_id']).astype({'teacher_id':'Int64', 'subject_id':'Int64', 'dept_id':'Int64'})

In [318]:
teacher

   teacher_id  subject_id  dept_id
0           1           2        3
1           1           2        4
2           1           3        3
3           2           1        1
4           2           2        1
5           2           3        1
6           2           4        1

In [327]:
df1=teacher.groupby('teacher_id').agg({'subject_id':'nunique'})
df1=df1.rename(columns={'subject_id':'cnt'})
#df1=df1['teacher_id','cnt']
df1

            cnt
teacher_id
1             2
2             4

In [387]:
###Write a solution to find the daily active user count for a period of 30 days ending 2019-07-27 inclusively.
##A user was active on someday if they made at least one activity on that day.

data = [[1, 1, '2019-07-20', 'open_session'], [1, 1, '2019-07-20', 'scroll_down'], [1, 1, '2019-07-20', 'end_session'], [2, 4, '2019-07-20', 'open_session'], [2, 4, '2019-07-21', 'send_message'], [2, 4, '2019-07-21', 'end_session'], [3, 2, '2019-07-21', 'open_session'], [3, 2, '2019-07-21', 'send_message'], [3, 2, '2019-07-21', 'end_session'], [4, 3, '2019-06-25', 'open_session'], [4, 3, '2019-06-25', 'end_session']]
activity = pd.DataFrame(data, columns=['user_id', 'session_id', 'activity_date', 'activity_type']).astype({'user_id':'Int64', 'session_id':'Int64', 'activity_date':'datetime64[ns]', 'activity_type':'object'})

In [388]:
activity

    user_id  session_id activity_date activity_type
0         1           1    2019-07-20  open_session
1         1           1    2019-07-20   scroll_down
2         1           1    2019-07-20   end_session
3         2           4    2019-07-20  open_session
4         2           4    2019-07-21  send_message
5         2           4    2019-07-21   end_session
6         3           2    2019-07-21  open_session
7         3           2    2019-07-21  send_message
8         3           2    2019-07-21   end_session
9         4           3    2019-06-25  open_session
10        4           3    2019-06-25   end_session

In [384]:
end_date=pd.to_datetime('2019-07-27')
end_date
start_date=end_date - pd.DateOffset(30)
start_date
activity['action']=activity['activity_date'].between(start_date,end_date)
activity

    user_id  session_id activity_date activity_type  action
0         1           1    2019-07-20  open_session    True
1         1           1    2019-07-20   scroll_down    True
2         1           1    2019-07-20   end_session    True
3         2           4    2019-07-20  open_session    True
4         2           4    2019-07-21  send_message    True
5         2           4    2019-07-21   end_session    True
6         3           2    2019-07-21  open_session    True
7         3           2    2019-07-21  send_message    True
8         3           2    2019-07-21   end_session    True
9         4           3    2019-06-25  open_session   False
10        4           3    2019-06-25   end_session   False

In [390]:
activity=activity[activity['action']==True]
#.groupby('activity_date').agg({'user_id':'nunique'})
activity=activity.groupby('activity_date').agg({'user_id':'nunique'})
activity=activity.rename(columns={'activity_date':'day', 'user_id':'active_users'}).reset_index()
activity

TypeError: DataFrame.rename() got an unexpected keyword argument 'column'

In [389]:
def user_activity(activity: pd.DataFrame) -> pd.DataFrame:
    end_date=pd.to_datetime('2019-07-27')
    start_date=end_date - pd.DateOffset(30)
    activity['action']=activity['activity_date'].between(start_date,end_date)
    activity=activity[activity['action']==True]
    activity=activity.groupby('activity_date').agg({'user_id':'nunique'})
    activity=activity.rename(columns={'activity_date':'day', 'user_id':'active_users'}).reset_index()
    return activity

user_activity(activity)

  activity_date  active_users
0    2019-07-20             2
1    2019-07-21             2

In [407]:
###Write a solution to find all sales that occurred in the first year each product was sold.
##For each product_id, identify the earliest year it appears in the Sales table.
##Return all sales entries for that product in that year.

data = [[1, 100, 2008, 10, 5000], [2, 100, 2009, 12, 5000], [7, 200, 2011, 15, 9000]]
sales = pd.DataFrame(data, columns=['sale_id', 'product_id', 'year', 'quantity', 'price']).astype({'sale_id':'Int64', 'product_id':'Int64', 'year':'Int64', 'quantity':'Int64', 'price':'Int64'})

sales

   sale_id  product_id  year  quantity  price
0        1         100  2008        10   5000
1        2         100  2009        12   5000
2        7         200  2011        15   9000

In [408]:
sales['first_year']=sales.groupby(['product_id'])[['year']].transform(min)
sales=sales[sales['year']==sales['first_year']].reset_index()
sales=sales[['product_id','first_year','quantity','price']]
sales

   product_id  first_year  quantity  price
0         100        2008        10   5000
1         200        2011        15   9000

In [417]:
###Write a solution to find all the classes that have at least five students.

data = [['A', 'Math'], ['B', 'English'], ['C', 'Math'], ['D', 'Biology'], ['E', 'Math'], ['F', 'Computer'], ['G', 'Math'], ['H', 'Math'], ['I', 'Math']]
courses = pd.DataFrame(data, columns=['student', 'class']).astype({'student':'object', 'class':'object'})

courses

  student     class
0       A      Math
1       B   English
2       C      Math
3       D   Biology
4       E      Math
5       F  Computer
6       G      Math
7       H      Math
8       I      Math

In [421]:
courses_cnt=courses.groupby('class')['student'].count().reset_index()
courses_cnt=courses_cnt[courses_cnt['student']>=5][['class']]
courses_cnt.reset_index()

   index class
0      3  Math

In [433]:
###Write a solution that will, for each user, return the number of followers.
##Return the result table ordered by user_id in ascending order.

data = [['0', '1'], ['1', '0'], ['2', '0'], ['2', '1']]
followers = pd.DataFrame(data, columns=['user_id', 'follower_id']).astype({'user_id':'Int64', 'follower_id':'Int64'})

In [434]:
followers

   user_id  follower_id
0        0            1
1        1            0
2        2            0
3        2            1

In [435]:
followers=followers.groupby('user_id').agg({'follower_id':'count'}).reset_index()
followers=followers.rename(columns = {'follower_id':'followers_count'})
followers

   user_id  followers_count
0        0                1
1        1                1
2        2                2

In [440]:
###A single number is a number that appeared only once in the MyNumbers table.
#Find the largest single number. If there is no single number, report null.

data = [[8], [8], [3], [3], [1], [4], [5], [6]]
my_numbers = pd.DataFrame(data, columns=['num']).astype({'num':'Int64'})

type(data)

list

In [437]:
data.drop_duplicates(keep = False).max().to_frame(name = 'num')
data

AttributeError: 'list' object has no attribute 'drop_duplicates'

In [439]:
data=data.drop_duplicates(keep = False).max().to_frame().T
data

AttributeError: 'list' object has no attribute 'drop_duplicates'

In [449]:
data = [[8], [8], [3], [3], [1], [4], [5], [6]]
df = pd.DataFrame(data, columns=['Numbers'])
df=df.drop_duplicates(keep=False).max()
df

Numbers    6
dtype: int64

In [442]:
df=df.drop_duplicates(keep = False).max().to_frame().T
df

   Numbers
0        6

In [491]:
## Write a solution to report the customer ids from the Customer table that bought all the products in the Product table.

data = [[1, 5], [2, 6], [3, 5], [3, 6], [1, 6]]
customer = pd.DataFrame(data, columns=['customer_id', 'product_key']).astype({'customer_id':'Int64', 'product_key':'Int64'})
data = [[5], [6]]
product = pd.DataFrame(data, columns=['product_key']).astype({'product_key':'Int64'})

In [492]:
product['cnt']=len(product['product_key'].drop_duplicates())
product

customer_fc=customer.groupby('customer_id').agg({'product_key':'nunique'}).reset_index().rename(columns={'product_key':'prod_cnt'})
customer_fc

   customer_id  prod_cnt
0            1         2
1            2         1
2            3         2

In [493]:
df=pd.merge(customer_fc,product,how='inner',left_on='prod_cnt',right_on='cnt')
df=df['customer_id'].drop_duplicates().reset_index()
df

0    1
2    3
Name: customer_id, dtype: Int64

In [498]:
def find_customers(customer: pd.DataFrame, product: pd.DataFrame) -> pd.DataFrame:
    product['cnt']=len(product['product_key'].drop_duplicates())
    customer_fc=customer.groupby('customer_id').agg({'product_key':'nunique'}).reset_index().rename(columns={'product_key':'prod_cnt'})
    df=pd.merge(customer_fc,product,how='inner',left_on='prod_cnt',right_on='cnt')
    df=df[['customer_id']].drop_duplicates()
    return df

find_customers(customer, product)

   customer_id
0            1
2            3

In [527]:
###we will consider a manager an employee who has at least 1 other employee reporting to them.
##Write a solution to report the ids and the names of all managers, the number of employees who report directly to them, and the average age of the reports rounded to the nearest integer.

data = [[9, 'Hercy', None, 43], [6, 'Alice', 9, 41], [4, 'Bob', 9, 36], [2, 'Winston', None, 37]]
employees = pd.DataFrame(data, columns=['employee_id', 'name', 'reports_to', 'age']).astype({'employee_id':'Int64', 'name':'object', 'reports_to':'Int64', 'age':'Int64'})


employees

   employee_id     name  reports_to  age
0            9    Hercy        <NA>   43
1            6    Alice           9   41
2            4      Bob           9   36
3            2  Winston        <NA>   37

In [529]:
df_emp=employees
df_mng=employees
df_mng=pd.merge()


#type(employees)
df_mng=df_emp.dropna(subset=['reports_to']).drop_duplicates()
df2=pd.merge(df_emp[['employee_id','name','age','reports_to']],df_mng[['reports_to','name']],how='inner',left_on='reports_to', right_on='reports_to')
df2=df2.drop_duplicates()
df2

   employee_id name_x  age  reports_to name_y
0            6  Alice   41           9  Alice
1            6  Alice   41           9    Bob
2            4    Bob   36           9  Alice
3            4    Bob   36           9    Bob

In [530]:
df_emp

   employee_id     name  reports_to  age
0            9    Hercy        <NA>   43
1            6    Alice           9   41
2            4      Bob           9   36
3            2  Winston        <NA>   37

In [531]:
df_mng

   employee_id   name  reports_to  age
1            6  Alice           9   41
2            4    Bob           9   36